services:
  ha-ipaper:
    image: ha-ipaper:latest
    container_name: ha-ipaper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - HA_IPAPER_GENERAL__homeassistant_url=http://homeassistant.local:8123
      - HA_IPAPER_GENERAL__homeassistant_token=YOUR_LONG_LIVED_ACCESS_TOKEN_HERE
    volumes:
      - /data/ha-ipaper:/config
    ports:
      - 8081:8081
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"